source 'https://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'page-object'
gem 'selenium-webdriver'
gem 'watir-webdriver'
gem 'syntax'
gem 'rack'
gem 'rspec'
gem 'yard'
gem 'yml_reader'
gem 'rubyzip'
gem 'builder'
gem 'logger'
gem 'faker'
gem 'gherkin'
gem 'mail'
gem 'data_magic'
gem 'viewcumber'
gem 'require_all'

#Database related gems
gem 'activerecord'
gem 'factory_girl'
gem 'database_cleaner'
gem 'sqlite3'